export const jobs = [
    {
        title: "Junior DevOps Engineer",
        location: "Remote",
        type: "Full-time",
        description: "We are looking for a Junior DevOps Engineer to join our team. This is a great opportunity for someone who is passionate about automation and cloud technologies.",
        qualifications: "1+ years of experience with AWS, Docker, and Kubernetes. Experience with CI/CD pipelines.",
        education: "Bachelor's degree in Computer Science or related field.",
        slug: "junior-devops-engineer",
    },
    {
        title: "Lead DevOps Engineer",
        location: "Remote",
        type: "Full-time",
        description: "We are looking for a Lead DevOps Engineer to join our team. You will be responsible for leading our DevOps team and mentoring junior engineers.",
        qualifications: "5+ years of experience with AWS, Docker, and Kubernetes. Experience with CI/CD pipelines. Experience with infrastructure as code (Terraform, CloudFormation).",
        education: "Bachelor's degree in Computer Science or related field.",
        slug: "lead-devops-engineer",
    },
    {
        title: "Technical Project Manager",
        location: "Remote",
        type: "Full-time",
        description: "We are looking for a Technical Project Manager to join our team. You will be responsible for managing our software development projects from start to finish.",
        qualifications: "3+ years of experience as a project manager in a software development environment. Experience with Agile methodologies.",
        education: "Bachelor's degree in Computer Science or related field.",
        slug: "technical-project-manager",
    },
    {
        title: "Client Aquisition Specialist",
        location: "Remote",
        type: "Full-time",
        description: "We are looking for a Client Aquisition Specialist to join our team. You will be responsible for generating new leads and closing deals.",
        qualifications: "2+ years of experience in sales or business development. Excellent communication and negotiation skills.",
        education: "Bachelor's degree in Business Administration or related field.",
        slug: "client-aquisition-specialist",
    },
    {
        title: "Full Stack Developer",
        location: "Remote",
        type: "Full-time",
        description: "We are looking for a Full Stack Developer to join our team. You will be responsible for developing and maintaining our web applications.",
        qualifications: "3+ years of experience with React, Node.js, and MongoDB. Experience with Next.js is a plus.",
        education: "Bachelor's degree in Computer Science or related field.",
        slug: "full-stack-developer",
    },
    {
        title: "Digital Marketing Specialist",
        location: "Remote",
        type: "Full-time",
        description: "We are looking for a Digital Marketing Specialist to join our team. You will be responsible for managing our social media accounts and creating marketing campaigns.",
        qualifications: "2+ years of experience in digital marketing. Experience with SEO, SEM, and social media marketing.",
        education: "Bachelor's degree in Marketing or related field.",
        slug: "digital-marketing-specialist",
    },
    {
        title: "Apply for Internship",
        location: "Remote",
        type: "Internship",
        description: "We are looking for interns to join our team. This is a great opportunity to gain experience in a fast-paced startup environment.",
        qualifications: "Currently enrolled in a Bachelor's or Master's degree program in Computer Science, Marketing, or Business.",
        education: "N/A",
        slug: "apply-for-internship",
    },
];